# Generated by Django 3.1 on 2022-04-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20220410_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='name_of_room',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='roommember',
            name='room_creater_channel',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='roommember',
            name='room_creater_name',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='roommember',
            name='room_creater_on_call',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='roommember',
            name='room_members',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roommember',
            name='room_record_flag',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
