# Generated by Django 3.1 on 2022-04-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20220412_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='name_of_room',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
