# Generated by Django 3.1 on 2022-04-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20220412_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomMemberMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomname', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('room_member_name', models.CharField(blank=True, default=None, max_length=1000, null=True)),
            ],
        ),
    ]
