# Generated by Django 3.1 on 2022-04-15 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_roommembermap'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='record_number',
            field=models.IntegerField(default=0),
        ),
    ]
