# Generated by Django 3.1 on 2022-04-15 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_record_record_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommembermap',
            name='user_channel',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
