# Generated by Django 3.1 on 2022-04-15 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_roommembermap_user_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommember',
            name='proxy_creater_channel',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='roommember',
            name='proxy_creater_name',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
