# Generated by Django 3.2.6 on 2022-04-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_auto_20220426_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommembermap',
            name='email',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
