# Generated by Django 3.2.6 on 2022-04-29 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_auto_20220429_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommemberhistory',
            name='date',
            field=models.CharField(default='29/4/2022', max_length=50),
        ),
    ]
