# Generated by Django 3.2.14 on 2022-07-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_alter_roommemberhistory_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommemberhistory',
            name='date',
            field=models.CharField(default='22/7/2022', max_length=50),
        ),
    ]
